"""Generate copy-paste log grep/rg commands for manual verification (like DB_VERIFY_QUERIES.sql)."""
from __future__ import annotations

import os
import re
import shlex
import subprocess
from pathlib import Path
from typing import Any

from audit_config import e2e_scenario_crns, scenario_description
from ticket_spec import scenarios


def _logs_dir() -> str:
    return (os.environ.get("LOGS_DIR") or "").strip()


def _default_log_patterns(sc: dict, crn: str) -> list[str]:
    """Patterns when ticket-spec omits log_patterns."""
    pats: list[str] = [crn]
    stan = os.environ.get("STAN", "")
    if stan:
        pats.append(stan)
    for step in sc.get("steps") or []:
        aid = step.get("api_id") or step.get("api")
        if aid:
            pats.append(str(aid))
    for code in ("4000373", "4000359", "4000028"):
        if code in (sc.get("name") or "") or any(
            code in str(step) for step in (sc.get("steps") or [])
        ):
            pats.append(code)
    # de-dupe preserve order
    seen: set[str] = set()
    out: list[str] = []
    for p in pats:
        if p and p not in seen:
            seen.add(p)
            out.append(p)
    return out


def scenario_log_patterns(sc: dict, crn: str) -> list[str]:
    explicit = [str(p) for p in (sc.get("log_patterns") or []) if p]
    if explicit:
        return explicit
    return _default_log_patterns(sc, crn)


def _grep_one(logs_dir: str, pattern: str, *, use_rg: bool) -> str:
    if use_rg:
        cmd = ["rg", "-n", "--no-heading", "-m", "20", pattern, logs_dir]
    else:
        cmd = [
            "grep",
            "-rn",
            "--include=*.log",
            "--include=*.out",
            "--include=*.err",
            "-m",
            "20",
            pattern,
            logs_dir,
        ]
    try:
        r = subprocess.run(cmd, capture_output=True, text=True, timeout=120)
        out = (r.stdout or "").strip()
        if not out and r.returncode not in (0, 1):
            return f"(search failed: {r.stderr.strip()[:200]})"
        return out or "(no matches)"
    except FileNotFoundError:
        return "(search tool not found — run commands below manually)"
    except subprocess.TimeoutExpired:
        return "(search timed out after 120s)"


def _shell_grep_line(logs_dir: str, pattern: str, *, use_rg: bool) -> str:
    pat_q = shlex.quote(pattern)
    dir_q = shlex.quote(logs_dir)
    if use_rg:
        return f'rg -n --no-heading -m 20 {pat_q} {dir_q}'
    return (
        f'grep -rn --include="*.log" --include="*.out" --include="*.err" '
        f"-m 20 {pat_q} {dir_q}"
    )


def write_log_verify_commands(
    ticket_dir: Path,
    spec: dict,
    base_crn: str,
    run_scenario_crns: dict[str, str] | None = None,
) -> Path | None:
    """Write LOG_VERIFY_COMMANDS.md with per-scenario grep/rg commands."""
    scenario_crns = e2e_scenario_crns(spec, base_crn, run_scenario_crns)
    logs_dir = _logs_dir()
    lines = [
        "# Log verification commands",
        "",
        "_Generated by Bob `validate-ticket`. Run on your machine where log files exist._",
        "",
    ]
    if not logs_dir:
        lines += [
            "## Setup required",
            "",
            "`LOGS_DIR` is not set. Add to `bob-the-builder/local/user.env` (via `bob setup`):",
            "",
            "```",
            "LOGS_DIR=C:/path/to/applogs/dsa",
            "```",
            "",
            "Typical Novopay QA layout:",
            "",
            "- `/apps/applogs/dsa/credit-card-management-dsa.log`",
            "- `/apps/applogs/dsa/api-gateway-dsa.log`",
            "",
            "Then re-run `bob validate-ticket <ticket-id>`.",
            "",
        ]
    else:
        lines.append(f"**LOGS_DIR:** `{logs_dir}`")
        lines.append("")

    lines += [
        "## Quick copy-paste (all E2E CRNs)",
        "",
    ]
    if scenario_crns:
        crn_list = " ".join(scenario_crns.values())
        if logs_dir:
            lines.append("```bash")
            lines.append(f'LOGS="{logs_dir}"')
            lines.append(f'rg -n "{base_crn}" "$LOGS" 2>/dev/null | head -50')
            for sid, crn in sorted(scenario_crns.items()):
                lines.append(f'# {sid}')
                lines.append(f'rg -n "{crn}" "$LOGS" 2>/dev/null | head -30')
            lines.append("```")
        lines.append("")

    lines += [
        "## Per scenario",
        "",
        "| Scenario | Description | CRN | Suggested patterns |",
        "|----------|-------------|-----|-------------------|",
    ]
    for sc in scenarios(spec):
        sid = sc.get("id", "?")
        if sid not in scenario_crns and (sc.get("verification_level") or "").lower() in (
            "integration",
            "e2e",
        ):
            continue
        if sid not in scenario_crns:
            continue
        crn = scenario_crns[sid]
        name = (sc.get("name") or "").replace("|", "\\|")[:80]
        pats = scenario_log_patterns(sc, crn)
        lines.append(
            f"| {sid} | {name} | `{crn}` | {', '.join(f'`{p}`' for p in pats[:6])} |"
        )

    lines += ["", "## Commands by scenario", ""]
    use_rg = False
    try:
        use_rg = subprocess.run(["rg", "--version"], capture_output=True).returncode == 0
    except (FileNotFoundError, OSError):
        use_rg = False

    for sc in scenarios(spec):
        sid = sc.get("id", "?")
        if sid not in scenario_crns:
            continue
        crn = scenario_crns[sid]
        name = sc.get("name", "")
        lines.append(f"### {scenario_description(sid, name)}")
        lines.append("")
        lines.append(f"- **CRN:** `{crn}`")
        if not logs_dir:
            lines.append("- _(set LOGS_DIR to enable runnable commands)_")
            lines.append("")
            continue
        lines.append("")
        lines.append("```bash")
        lines.append(f'LOGS={shlex.quote(logs_dir)}')
        for pat in scenario_log_patterns(sc, crn):
            lines.append(f"# pattern: {pat}")
            lines.append(_shell_grep_line(logs_dir, pat, use_rg=use_rg))
        lines.append("```")
        lines.append("")

    out = ticket_dir / "LOG_VERIFY_COMMANDS.md"
    out.write_text("\n".join(lines), encoding="utf-8")
    return out


def run_log_search_script(ticket_dir: Path, spec_path: Path | None = None) -> tuple[bool, str]:
    """Run log search when LOGS_DIR is set; writes log-search.txt (Python on Windows)."""
    logs_dir = _logs_dir()
    if not logs_dir:
        return False, "LOGS_DIR not set (skip log search)"
    if not Path(logs_dir).is_dir():
        return False, f"LOGS_DIR not a directory: {logs_dir}"
    spec_path = spec_path or ticket_dir / "ticket-spec.yaml"
    if not spec_path.exists():
        return False, "ticket-spec.yaml missing"
    if os.name == "nt":
        return _run_log_search_python(ticket_dir, spec_path, logs_dir)
    script = Path(__file__).resolve().parents[1] / "search-logs.sh"
    if not script.exists():
        return False, "search-logs.sh not found"
    try:
        r = subprocess.run(
            ["bash", str(script), str(spec_path)],
            capture_output=True,
            text=True,
            timeout=300,
            cwd=str(script.parent),
        )
        msg = (r.stdout or r.stderr or "").strip()[-500:]
        if r.returncode == 0:
            return True, f"log-search.txt written ({logs_dir})"
        return False, f"search-logs.sh exit {r.returncode}: {msg}"
    except Exception as e:
        return False, str(e)


def _run_log_search_python(ticket_dir: Path, spec_path: Path, logs_dir: str) -> tuple[bool, str]:
    """Windows-safe log grep without invoking search-logs.sh."""
    from ticket_spec import load

    try:
        spec = load(spec_path)
    except Exception as exc:
        return False, f"ticket-spec load failed: {exc}"
    base_crn = ""
    summary_path = ticket_dir / "run-summary.json"
    if summary_path.is_file():
        try:
            import json

            data = json.loads(summary_path.read_text(encoding="utf-8"))
            base_crn = str((data.get("decisions") or {}).get("crn") or "")
        except (OSError, json.JSONDecodeError):
            pass
    scenario_crns = e2e_scenario_crns(spec, base_crn or "TDD")
    lines: list[str] = [f"# log-search (python) LOGS_DIR={logs_dir}", ""]
    root = Path(logs_dir)
    for sc in scenarios(spec):
        sid = sc.get("id", "?")
        if sid not in scenario_crns:
            continue
        crn = scenario_crns[sid]
        lines.append(f"## {sid} CRN={crn}")
        for pat in scenario_log_patterns(sc, crn):
            hits = 0
            for log in root.rglob("*.log"):
                try:
                    text = log.read_text(encoding="utf-8", errors="replace")
                except OSError:
                    continue
                for i, line in enumerate(text.splitlines(), 1):
                    if pat in line:
                        lines.append(f"{log.name}:{i}:{line[:200]}")
                        hits += 1
                        if hits >= 20:
                            break
                if hits >= 20:
                    break
            if hits == 0:
                lines.append(f"(no matches for {pat!r})")
        lines.append("")
    out_path = ticket_dir / "log-search.txt"
    out_path.write_text("\n".join(lines), encoding="utf-8")
    return True, f"log-search.txt written ({logs_dir}, python)"
