#!/usr/bin/env bash
# Interactive / env-based config for TDD runner. Source from other scripts.
set -euo pipefail

TDD_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# Host repo: BOB_HOST_REPO, else cwd (validate-ticket sets cwd), else parent of runner install
if [[ -n "${BOB_HOST_REPO:-}" && -d "$BOB_HOST_REPO" ]]; then
  REPO_ROOT="$(cd "$BOB_HOST_REPO" && pwd)"
elif [[ -d "${PWD}/.git" ]] || [[ -d "${PWD}/docs/tdd-runs" ]]; then
  REPO_ROOT="$(pwd)"
else
  REPO_ROOT="$(cd "$TDD_ROOT/../.." && pwd)"
fi
export TDD_ROOT REPO_ROOT

# --- Defaults (override via env or tdd.env) ---
export MYSQL_HOST="${MYSQL_HOST:-127.0.0.1}"
export MYSQL_PORT="${MYSQL_PORT:-3306}"
export MYSQL_USER="${MYSQL_USER:-root}"
export MYSQL_PASS="${MYSQL_PASS:-root}"
export CC_BASE="${CC_BASE:-http://localhost:8016/cc-mgmt}"
export MD_BASE="${MD_BASE:-http://localhost:8015/masterdata}"
export LOGS_DIR="${LOGS_DIR:-}"
export TDD_RUN_DIR="${TDD_RUN_DIR:-}"
export TDD_NONINTERACTIVE="${TDD_NONINTERACTIVE:-0}"

load_tdd_env() {
  local f="${1:-$TDD_RUN_DIR/tdd.env}"
  if [[ -f "$f" ]]; then
    set -a
    # shellcheck source=/dev/null
    source "$f"
    set +a
  fi
  return 0
}

find_mysql() {
  if command -v mysql >/dev/null 2>&1; then echo mysql; return; fi
  local win="/c/Program Files/MySQL/MySQL Server 8.0/bin/mysql.exe"
  [[ -f "$win" ]] && echo "$win" && return
  echo "ERROR: mysql client not found" >&2
  return 1
}

mysql_ping() {
  local bin="${1:?mysql bin required}"
  local db="${2:-mysql}"
  "$bin" -h"$MYSQL_HOST" -P"$MYSQL_PORT" -u"$MYSQL_USER" -p"$MYSQL_PASS" -e "SELECT 1" "$db" >/dev/null 2>&1
}

prompt_if_empty() {
  local varname="$1" prompt="$2" default="${3:-}"
  local val="${!varname:-}"
  if [[ -n "$val" ]]; then return; fi
  if [[ "$TDD_NONINTERACTIVE" == "1" ]]; then
    val="$default"
  else
    read -r -p "$prompt [$default]: " val || true
    val="${val:-$default}"
  fi
  printf -v "$varname" '%s' "$val"
  export "$varname"
}

ensure_mysql_creds() {
  local bin
  bin="$(find_mysql)" || return 1
  if mysql_ping "$bin"; then
    export MYSQL_BIN="$bin"
    return 0
  fi
  echo "MySQL login failed for user=$MYSQL_USER host=$MYSQL_HOST (default password root)."
  if [[ "$TDD_NONINTERACTIVE" == "1" ]]; then
    echo "Set MYSQL_PASS (and MYSQL_USER) in tdd.env or env." >&2
    return 1
  fi
  read -r -p "MySQL password: " -s MYSQL_PASS
  echo
  prompt_if_empty MYSQL_USER "MySQL user" "root"
  prompt_if_empty MYSQL_HOST "MySQL host" "127.0.0.1"
  prompt_if_empty MYSQL_PORT "MySQL port" "3306"
  if mysql_ping "$bin"; then
    export MYSQL_BIN="$bin"
    return 0
  fi
  read -r -p "MySQL password (retry): " -s MYSQL_PASS
  echo
  mysql_ping "$bin" || { echo "MySQL still failing." >&2; return 1; }
  export MYSQL_BIN="$bin"
}

ensure_logs_dir() {
  prompt_if_empty LOGS_DIR "Logs directory (files searched recursively)" "$REPO_ROOT"
  if [[ ! -d "$LOGS_DIR" ]]; then
    echo "WARN: LOGS_DIR does not exist: $LOGS_DIR — creating for report only"
    mkdir -p "$LOGS_DIR" 2>/dev/null || true
  fi
  export LOGS_DIR
}

save_tdd_env() {
  local dir="${1:-$TDD_RUN_DIR}"
  mkdir -p "$dir"
  cat >"$dir/tdd.env" <<EOF
# Generated by Bob the Builder — safe to edit and re-run
NOVOPAY_WORKSPACE_ROOT=${NOVOPAY_WORKSPACE_ROOT:-}
MYSQL_HOST=$MYSQL_HOST
MYSQL_PORT=$MYSQL_PORT
MYSQL_USER=$MYSQL_USER
MYSQL_PASS=$MYSQL_PASS
CC_BASE=$CC_BASE
MD_BASE=$MD_BASE
LOGS_DIR=$LOGS_DIR
EOF
}
